#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use CoG\Less\Command\BuildCommand;

$application = new Application();
$application->add(new BuildCommand());
$application->run();
